title: Mohamed Eid
logo: Images/Untitled design.jpg
description: ""
show_downloads: false
theme: jekyll-theme-minimal


## Contact

- [LinkedIn](https://www.linkedin.com/in/mohamed-eid-972958206/)
- Email: m.h.m.h.eid1-24@student.lboro.ac.uk
- Phone: +44 7849045558
